### ISSUE TITLE
Vaultec

### ISSUE THREAD

**Issue by vaultec81** [3box/ceramic-anchor-allowlist#11]
# Team:
vaultec

# Discord
vaultec#0001

# Use Case

Personal infrastructure for use across internal and external projects as they become relevant.

# Overview

Dedicated server/colocation

Docker container using external go-ipfs instance

## Ceramic State Store persistence

ZFS RAID

## IPFS Repo persistence:

ZFS RAID

## Static Egress IP:

* 185.130.44.194/32
* 167.160.89.98/29 (98, 99, 100, 101, 102)

**Comment by smrz2001** [comment]
:shipit:
