### ISSUE TITLE
Gitcoin Passport

### ISSUE THREAD

**Issue by shavinac** [3box/ceramic-anchor-allowlist#13]
# Team

Gitcoin

# Discord

shacha#9406

# Use Case

We are using Ceramic to store user "passports" which will contain Verifiable Credentials (also stored on Ceramic) and some metadata, and these passports will be publicly readable so that users can bring their passports to any application. Our Ceramic node will primarily be used for reading and writing this data from our client applications.

# Overview

The Ceramic and IPFS nodes are currently running in AWS as containers in ECS. Each container is currently allocated 2 vCPU and 4 GB memory.

## Ceramic State Store persistence

We are running the `ceramicnetwork/js-ceramic:latest` Docker image enabled with S3 data storage.

## IPFS Repo persistence:

We are running the `ceramicnetwork/go-ipfs-daemon:latest` Docker image enabled with S3 data storage.

## Static Egress IP:

`34.236.75.99`
`35.170.181.124`

**Comment by smrz2001** [comment]
Done :shipit:
