### ISSUE TITLE
Disco

### ISSUE THREAD

**Issue by aldigjo** [3box/ceramic-anchor-allowlist#14]
# Team

Disco.xyz

# Discord
aldigjo#5069

# Use Case
We are using ceramic to store user profiles and verifiable credentials. These will be public with some verifiable credentials potentially being encrypted. Our node will be used for writing/reading such data. 

# Overview
We are running our nodes using Kubernetes on digital ocean.

## Ceramic State Store persistence
We are assigning it to a persistent volume claim within the Kubernetes configuration. 

## IPFS Repo persistence:
We are assigning it to a persistent volume claim within the Kubernetes configuration. 

## Static Egress IP:
146.190.0.104

**Comment by aldigjo** [comment]
@smrz2001 apologies, updated

**Comment by smrz2001** [comment]
No worries, @aldigjo, thanks!

Done! 🚀
