### ISSUE TITLE
Lumos

### ISSUE THREAD

**Issue by FleetingTimePaul** [3box/ceramic-anchor-allowlist#15]
# Team
lumosprotocol

# Discord
Lumos#5763

# Use Case
We are using ceramic to store user profiles.  Our node will be used for writing/reading such data.

# Overview
We are running our nodes on amazon cloud server.

## Ceramic State Store persistence
We are assigning it to a persistent volume claim within the Kubernetes configuration.

## IPFS Repo persistence:
We are assigning it to a persistent volume claim within the Kubernetes configuration.

## Static Egress IP:
52.69.45.131

**Comment by smrz2001** [comment]
Done! 🚀
