### ISSUE TITLE
Disco

### ISSUE THREAD

**Issue by Eseoghene** [3box/ceramic-anchor-allowlist#16]
# Team

Disco

# Discord
Ese#9987

# Use Case
We are using ceramic to store user profiles and verifiable credentials. These will be public with some verifiable credentials potentially being encrypted. Our node will be used for writing/reading such data.

# Overview
We are running our nodes using Kubernetes on digital ocean.

## Ceramic State Store persistence
We are assigning it to a persistent volume claim within the Kubernetes configuration.

## IPFS Repo persistence:
We are assigning it to a persistent volume claim within the Kubernetes configuration.

## Static Egress IP:
143.244.209.130

**Comment by smrz2001** [comment]
Done 🚀
