### ISSUE TITLE
MetaGame

### ISSUE THREAD

**Issue by polimyl** [3box/ceramic-anchor-allowlist#18]
# Team
[MetaGame](https://wiki.metagame.wtf) ([github](https://github.com/MetaFam))

# Discord
Polimyl#6848

# Use Case
Our Ceramic node will be used for [MyMeta](https://my.metagame.wtf) to save our users' basicProfile, an extended profile set, skills description, and account verifications from IdentityLink.

# Overview
We are running both Ceramic and out-of-process IPFS Docker containers in a Google Kubernetes cluster.

## Ceramic State Store persistence
Each container mounts a persistent volume on it's data directory. These volumes also get snapshotted every 8 hours.

## IPFS Repo persistence:
See above

## Static Egress IP:
34.85.157.166

Note: this is a resubmit of our [peerlist pr](https://github.com/ceramicnetwork/peerlist/pull/58) since our egress IP has changed and needs to be whitelisted again.

**Comment by smrz2001** [comment]
Done 🚢
