### ISSUE TITLE
111

### ISSUE THREAD

**Issue by wuxkui** [3box/ceramic-anchor-allowlist#20]
# Team
Babylon

# Discord
Oxyoung#7800

# Use Case
Offering nodes as a service to other apps

# Overview

4vcpu-4gb-50gb

version: "3"

services:
    lotus:
        container_name: js-ceramic
        image:  ceramicnetwork/js-ceramic:develop
        restart: always
        volumes:
         - ./:/root/.ceramic
         - ./logs:/root/.ceramic/logs # Path to daemon logs
         - ./statestore:/root/.ceramic/statestore
        network_mode: host
        tty: trueversion: "3"

services:
    lotus:
        container_name: ipfs
        image: ceramicnetwork/go-ipfs-daemon 
        restart: always
        volumes:
            - /home/ipfs:/data/ipfs
        network_mode: host
        tty: true
        environment:
            TZ: Asia/Shanghaiversion: "3"

## Ceramic State Store persistence

Making periodic volume snapshots
## IPFS Repo persistence:

Making periodic volume snapshots

**Comment by smrz2001** [comment]
Done 🚀

**Comment by smrz2001** [comment]
Hi! We're excited to see what apps you're working with. Can you please send us the link to any app you're serving through your node?

We're auditing our firewall rules and will be cleaning up entries that are not being actively used.

**Comment by smrz2001** [comment]
cc @wuxkui
