### ISSUE TITLE
byb_crypto_node_center

### ISSUE THREAD

**Issue by baiyibo** [3box/ceramic-anchor-allowlist#22]
Team
byb

Discord
byb5811022#3590

Use Case
Offering node as a service for other dapps

Overview
4vcpu-8gb-100gb
version: "2"
services:
lotus:
container_name: js-ceramic
image: ceramicnetwork/js-ceramic:testnet-clay
restart: always
volumes:

./:/root/.ceramic
./logs:/root/.ceramic/logs # Path to daemon logs
./statestore:/root/.ceramic/statestore
Ceramic State Store persistence
Making periodic volume snapshots

IPFS Repo persistence:
Making periodic volume snapshots

Static Egress IP:
121.5.102.39

**Comment by smrz2001** [comment]
Is this for running your node on Clay?

**Comment by smrz2001** [comment]
You should be all set to run on Clay 👍🏼 Please use network `testnet-clay`.
