### ISSUE TITLE
nekonikoban

### ISSUE THREAD

**Issue by nekokoban-kasoutuu** [3box/ceramic-anchor-allowlist#25]
# Team
nekonikoban

# Discord
nekonikoban#9989

# Use Case
Offering nodes as a service to other apps

# Overview
-6vcpu-8gb-160gb
-already running on testnet
-request for access to mainnet

// docker-compose.yaml
version: "3.7"
services:
    js-ceramic:
        container_name: js-ceramic
        image: ceramicnetwork/js-ceramic:latest
        restart: always
        ports:
            - "7007:7007"
        volumes:
            - ./:/root/.ceramic
            - ./logs:/root/.ceramic/logs
            - ./statestore:/root/.ceramic/statestore
        network_mode: host
        tty: true

    ipfs:
        container_name: ipfs
        image: ceramicnetwork/go-ipfs-daemon:latest
        restart: always
        ports:
            - "5001:5001"
            - "8011:8011"
        volumes:
            - ./data:/data
        network_mode: host
        tty: true

## Ceramic State Store persistence
Making periodic volume snapshots

## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
http://164.70.93.214:7007/api/v0/node/healthcheck
alive.

**Comment by smrz2001** [comment]
Hi! We're excited to see what apps you're working with. Can you please send us the link to any app you're serving through your Clay node?

**Comment by smrz2001** [comment]
cc @nekokoban-kasoutuu
