### ISSUE TITLE
gunu-node

### ISSUE THREAD

**Issue by liray-unendlich** [3box/ceramic-anchor-allowlist#27]
# Team
gunu-node

# Discord
liray#7929

# Use Case
Offer nodes as a service to other apps and as a infrastructure of ceramic.

# Overview
Running ceramic node and ipfs node with docker swarm.
Also, I am monitoring my node load with grafana/prometheus.
Node spec:
CPU: 6c12t
RAM: 32GB
Storage: 960GB SSD

## Ceramic State Store persistence
Using persistent volumes and snapshotting them frequently

## IPFS Repo persistence:
Using persistent volumes and snapshotting them frequently

## Static Egress IP:
167.179.90.227

**Comment by smrz2001** [comment]
Hi! We're excited to see what apps you're working with. Can you please send us the link to any app you're serving through your Clay node?

**Comment by smrz2001** [comment]
cc @liray-unendlich
