### ISSUE TITLE
APEX

### ISSUE THREAD

**Issue by apex213** [3box/ceramic-anchor-allowlist#28]
# Team
APEX

# Discord
APEX999#2447

# Use Case
Offering nodes as a service to other apps

# Overview
3vcpu-3gb-400gb
-already running on testnet
-request for access to mainnet

version: "3.7"
services:
    js-ceramic:
        container_name: js-ceramic
        image: ceramicnetwork/js-ceramic:latest
        restart: always
        ports:
            - "7007:7007"
        volumes:
            - ./:/root/.ceramic
            - ./logs:/root/.ceramic/logs
            - ./statestore:/root/.ceramic/statestore
        network_mode: host
        tty: true

    ipfs:
        container_name: ipfs
        image: ceramicnetwork/go-ipfs-daemon:latest
        restart: always
        ports:
            - "5001:5001"
            - "8011:8011"
        volumes:
            - ./data:/data
        network_mode: host

## Ceramic State Store persistence
Making periodic volume snapshots

## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
http://133.18.229.191:7007/api/v0/node/healthcheck
Alive!

**Comment by smrz2001** [comment]
Hi! We're excited to see what apps you're working with. Can you please send us the link to any app you're serving through your Clay node?

**Comment by smrz2001** [comment]
cc @apex213
