### ISSUE TITLE
TwoCents

### ISSUE THREAD

**Issue by drsmog** [3box/ceramic-anchor-allowlist#29]
# Team

Twocents (drsmog,WizardOfAus)

https://twocents.so
https://alpha.twocents.so

# Discord

IKA#5166

# Use Case

we are developing and migrating our app on ceramic (https://alpha.twocents.so) to be more decentralized.
Usecase is that users will save their profile and verified credentials(reputation) in a ceramic network instead of saving it in a centralized DB

Example of profile: https://alpha.twocents.so/people/vitalik.eth 

we want to make this page work through ceramic

# Overview
How are you running your nodes? What cloud infrastructure? How are you running your IPFS node(s)?
Currently, we are using AWS infrastructure

running 2 EC2 machines both t2.medium with EBS storage
plus 2 application load balancers for IPFS node and for Ceramic node separately
we are using docker containers inside these EC2 machines to run IPFS and Ceramic

## Ceramic State Store persistence
We are using EBS mounted volumes on those machines monitoring them frequently taking snapshots

## IPFS Repo persistence:
We are using EBS mounted volumes on those machines monitoring them frequently taking snapshots

## Static Egress IP:

13.41.237.174

**Comment by smrz2001** [comment]
Done 🚀

**Comment by drsmog** [comment]
cool thanks @smrz2001
