### ISSUE TITLE
[Replace me with Project Name]

### ISSUE THREAD

**Issue by NicWickman** [3box/ceramic-anchor-allowlist#31]
# Team

Cambrian Protocol

# Discord
TRUTH#7988

# Use Case
Managing user profiles, data for a staged smart contract configuration pipeline, proposal and chat data and misc. other data related to Cambrian Protocol's Future of Work platform.

# Overview
GCE VM using the node daemon.

## Ceramic State Store persistence
Mounted persistent disk storage with regular backups

## IPFS Repo persistence:
Mounted persistent disk storage with regular backups

## Static Egress IP:
Static *egress* IP address of the machine your Ceramic daemon runs on so it can connect to the 3Box Labs hosted Ceramic Anchor Service (CAS)
35.224.77.11

**Comment by smrz2001** [comment]
Done! 🚀:shipit:

Please let me know if your prod Ceramic node is now able to come up successfully.
