### ISSUE TITLE
TestProject

### ISSUE THREAD

**Issue by temaniarpit27** [3box/ceramic-anchor-allowlist#32]
# Team
Individual - temaniarpit27

# Discord
temaniarpit27#0456

# Use Case
Personal Project

# Overview

Node -
Amazon AWS - 16GB, 1TB

## Ceramic State Store persistence
Local storage. I will move to S3 shortly

## IPFS Repo persistence:
Local storage. I will move to S3 shortly

## Static Egress IP:
13.233.3.198

## Working testnet node
`curl http://13.233.3.198:7007/api/v0/node/healthcheck`

**Comment by smrz2001** [comment]
Hi @temaniarpit27, what kind of project are you building? We'd be interested in understanding it better.

Can we see it running on testnet?

**Comment by smrz2001** [comment]
@temaniarpit27, you can reply to this ticket when you have more details.
