### ISSUE TITLE
Mach34

### ISSUE THREAD

**Issue by Ian-Bright** [3box/ceramic-anchor-allowlist#33]
# Team
https://github.com/Mach-34

# Discord
Brightir#8154

# Use Case
A few colleagues in the web3 space have expressed interest to us that they would like to bring their project to the ceramic mainnet but do not want to set up the infrastructure themselves to run a mainnet node. We are looking to run some tests on a node anchored to the mainnet to determine the validity of providing access to the node to multiple parties via a shared api

# Overview
Running ceramic node and IPFS inside of AWS

## Ceramic State Store persistence
Writing to S3 bucket

## IPFS Repo persistence:
Writing to S3 bucket

## Static Egress IP:
13.59.218.138

**Comment by smrz2001** [comment]
Done 🚀
