### ISSUE TITLE
Metokens

### ISSUE THREAD

**Issue by zgorizzo69** [3box/ceramic-anchor-allowlist#34]
# Team

meTokens

# Discord

CBobRobison | meTokens#9953
zgo#4684

# Use Case
store decntralized data

# Overview
yes running our own nodes on aws  
 
## Ceramic State Store persistence
aws S3 + backup on another S3 provider 

## IPFS Repo persistence:
pinned to pinata

## Static Egress IP:
 54.211.141.15

check out app.metokens.com

**Comment by smrz2001** [comment]
🚀
