### ISSUE TITLE
EPNS

### ISSUE THREAD

**Issue by strykerin** [3box/ceramic-anchor-allowlist#35]
# Team
EPNS

# Discord
Balkage#7666

# Use Case
DID for chat application

# Overview
We are running our nodes on EC2

## Ceramic State Store persistence
Data stored on mount disk with snapshots taken automatically

## IPFS Repo persistence:
Data stored on mount disk with snapshots taken automatically

## Static Egress IP:
3.215.201.143

**Comment by smrz2001** [comment]
🚀
