### ISSUE TITLE
Mach34 Terraform

### ISSUE THREAD

**Issue by Ian-Bright** [3box/ceramic-anchor-allowlist#37]
# Team
Mach34

Team name or your github handle if you are a team of one.
https://github.com/Mach-34

# Discord
Brightir#8154
jp4g#1337

# Use Case
Same use case as this: https://github.com/3box/ceramic-anchor-allowlist/issues/33. But unlike a custom setup we would like to test a terraform implementation

# Overview
AWS

## Ceramic State Store persistence
S3 versioning brought by Terraform replicated across availability zones

## IPFS Repo persistence:
S3 versioning brought by Terraform replicated across availability zones

## Static Egress IP:
18.219.208.129

**Comment by smrz2001** [comment]
:shipit:
