### ISSUE TITLE
Geo Web

### ISSUE THREAD

**Issue by codynhat** [3box/ceramic-anchor-allowlist#41]
# Team

The [Geo Web](https://www.geoweb.network) is a protocol for anchoring digital content to physical land. We are currently using an ELP node provided by 3box Labs, but would like to replace this with our own dedicated node.

# Discord
codynhat#7156

# Use Case
We use Ceramic to attach various digital content to physical land, using Tile documents.

# Overview
We are using Kubernetes inside of Digital Ocean to run the node as well as an IPFS node.

## Ceramic State Store persistence
We are using the S3 state store powered by Digital Ocean's Spaces, which is S3 compatible. We are currently using a fork of `js-ceramic` that has this PR merged: https://github.com/ceramicnetwork/js-ceramic/pull/2551#issuecomment-1319146259

## IPFS Repo persistence:
We are also using an S3 store for IPFS.

## Static Egress IP:
157.230.181.252
157.230.181.128
146.190.196.39
206.189.255.126

**Comment by v-stickykeys** [comment]
Added!
