### ISSUE TITLE
HireNodes: MeTokens Ceramic Cluster

### ISSUE THREAD

**Issue by kammerdiener** [3box/ceramic-anchor-allowlist#43]
# Team
HireNodes

# Discord
kammerdiener#6620

# Use Case
MeTokens

# Overview
Ceramic and IPFS are running as individual VMs in Vultr.

## Ceramic State Store persistence
Stored locally and snapshot daily. 

## IPFS Repo persistence:
Stored locally and snapshot daily. Additional backups will be copying IPFS off and into a different location daily. 

## Static Egress IP: 
45.32.91.151

**Comment by smrz2001** [comment]
:rocket:
