### ISSUE TITLE
Carbon Title Building Ownership

### ISSUE THREAD

**Issue by lroder-ct** [3box/ceramic-anchor-allowlist#44]
# Team
Carbon Title
Team name or your github handle if you are a team of one.

# Discord
Your discord username. ex. Bob#3312
lroder#9033
# Use Case
A few words on your project use case, what your node will be used for, and how you're using ceramic so we can make recommendations for your setup
To store building metadata, including carbon footprint, carbon credits, on the blockchain
# Overview
How are you running your nodes? What cloud infrastructure? How are you running your IPFS node(s)?
AWS - internal ceramic nodes (dev, qa, staging, prod) run as EC2's, internal apps a mixture of ECS, EKS, Lambda
## Ceramic State Store persistence
What are you doing to ensure your Ceramic data doesn't get lost?
ceramis and ipfs kubo data store locate on a separate EBS volume
## IPFS Repo persistence:
What are you doing to ensure your IPFS data doesn't get lost?
AWS backup plan - daily backups
## Static Egress IP:
Static *egress* IP address of the machine your Ceramic daemon runs on so it can connect to the 3Box Labs hosted Ceramic Anchor Service (CAS)
35.84.164.207

**Comment by 3benbox** [comment]
Added 🚀
