### ISSUE TITLE
Protico - Web3 Chatting Network

### ISSUE THREAD

**Issue by howieyoung** [3box/ceramic-anchor-allowlist#45]
# Team
Protico, a leading project in the Web3 Chat space.
We aim to create a universal Web3-based chatting interface across all apps and websites.

# Discord
Hy | Protico#1320

# Use Case
Protico is making a Web3 chatting network that connects users' wallets to manage their social graph and chat records.

# Overview
The node will be mainly uses to handle the social assets that our users generate.

## Ceramic State Store persistence
We are using  AWS S3 (state-store-s3-bucket).

## IPFS Repo persistence:
We are also using an S3 for IPFS repo, sync its EFS to S3 periodically.

## Static Egress IP:
50.17.239.165

**Comment by howieyoung** [comment]
[@v-stickykeys](https://github.com/v-stickykeys)
[@smrz2001](https://github.com/smrz2001)

Please review our application and process it. Thanks!

**Comment by smrz2001** [comment]
Done 🚀
