### ISSUE TITLE
Spect Network

### ISSUE THREAD

**Issue by avp1598** [3box/ceramic-anchor-allowlist#46]
# Team
Spect Network

# Discord
0xavp.eth | spect.network#4305

# Use Case
Spect network is a OSS to help web3 orgs centralize context & decentralize decision making. We have different components in our tool such as forms/projects. We are using ceramic to store form responses using ComposeDB

# Overview
Running a small digital ocean droplet of 1 GB ram and  25 GB disk. It has both ceramic and IPFS service running.

## Ceramic State Store persistence
Data is persisted in local storage at the moment

## IPFS Repo persistence:
Data is persisted in local storage at the moment

## Static Egress IP:
167.99.152.53

**Comment by avp1598** [comment]
@smrz2001 please take a look!

**Comment by smrz2001** [comment]
Done 🚀
