### ISSUE TITLE
Rehoboam

### ISSUE THREAD

**Issue by Fooooooooooox** [3box/ceramic-anchor-allowlist#6]
#Rehoboam

# Discord
#9921

# Use Case
We will use ceramic to build a Web3 smart messaging protocol. This will support functions such as Wallet-to-Wallet Chat, information subscription, In-Dapp Notifications, etc. The protocol will have strong extensibility, allowing developers to define different functions according to their needs.

# Overview
running on tencent cloud server with out of process ipfs 

## Ceramic State Store persistence
we take snapshot of data automatically

## IPFS Repo persistence:
we take snapshot of data automatically

## Static Egress IP:
101.35.25.157

**Comment by Fooooooooooox** [comment]
@v-stickykeys i don't know how to add assignee for my issue...
so i just mention you here(hope this will work

**Comment by smrz2001** [comment]
Thanks, @Fooooooooooox. Your egress IP address has been added to the CAS allowlist 🚀

**Comment by Fooooooooooox** [comment]
thankyou! i ran it on testnet, how can i change it into mainnet?
