### ISSUE TITLE
C-Voxel

### ISSUE THREAD

**Issue by kitakaze-kan** [3box/ceramic-anchor-allowlist#9]
# Team

kitakaze-kan

# Discord
0xKantaro | C-Voxel#4407

# Use Case
To Store user's C-Voxel data on Ceramic Network.
C-Voxel is the user's web3 work history generated as part of Verifiable Credentials from the user's on-chain transaction hash, the work details related to the transaction, and the user's signature.

# Overview
We are running the v2 Ceramic node in AWS using the terraform module. IPFS out of process.
Also, We are using s3 buckets for persistence.

## Ceramic State Store persistence
Taking snapshot of data automatically

## IPFS Repo persistence:
Taking snapshot of data automatically

## Static Egress IP:
3.223.132.101

**Comment by smrz2001** [comment]
Hi @kitakaze-kan, can you add the egress IP address to the issue? We won't be able to use the URL you've specified, I'm afraid ☹️

**Comment by kitakaze-kan** [comment]
@smrz2001 sorry for my mistake. I added static IP :)

**Comment by smrz2001** [comment]
Thanks, @kitakaze-kan.

This looks like an internal IP address though. Can you provide a *public* IP address?

Since you're using AWS Terraform module, you can use these instructions to expose a public IP address for your ECS service.

https://aws.amazon.com/premiumsupport/knowledge-center/ecs-fargate-static-elastic-ip-address/

**Comment by kitakaze-kan** [comment]
Thanks @smrz2001 and sorry again.
here is public IP(Elastic IP) and I updated the issue.
3.223.132.101

Is that correct? Or do I need to add it manually?

**Comment by smrz2001** [comment]
Which resource is this public IP for, @kitakaze-kan?

**Comment by smrz2001** [comment]
Oh cool, ok, I think that should work - I added your public IP to the firewall.

Can you try bringing up your Ceramic node and see if it's able to access the CAS? It won't come up if connectivity is faulty.

Will keep the issue open till we make sure the connectivity is working 👍🏼

**Comment by smrz2001** [comment]
Tagging @v-stickykeys in this issue since I will be out for the next couple of days.

**Comment by kitakaze-kan** [comment]
@smrz2001 @v-stickykeys Thanks sooo much!
Now I successfully got my node up and running.

**Comment by smrz2001** [comment]
Great! 😁
